# This is a basic workflow to help you get started with Actions

name: MLOps Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      

    - name: Build Docker image
      run: docker build -t imagemlops .

    - name: Run Docker container (optional)
      run: docker run imagemlops

    - name: Push Docker image to registry (optional)
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push imagemlops

    - name: Execute Python scripts in Docker container
      run: docker run imagemlops python preprocess_data.py

    - name: Execute training script
      run: docker run imagemlops python train_model.py

    - name: Execute prediction script (optional)
      run: docker run imagemlops python predict_response.py

    - name: Clean up
      run: docker system prune --force
